spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/a4
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  hazelcast:
    config:
      classpath: hazelcast.xml

    
server:
   port: 8083